<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjgcj2m\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjgcj2m/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTjgcj2m.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTjgcj2m\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTjgcj2m\appDevDebugProjectContainer();
